# Generated by Django 5.0.7 on 2024-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Video_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_videos',
            field=models.ManyToManyField(related_name='favorited_by_users', to='Video_App.video'),
        ),
    ]
