# Generated by Django 5.0.7 on 2024-07-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_favorite_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_videos',
        ),
    ]
