# Generated by Django 5.0.7 on 2024-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
