# Generated by Django 5.0.7 on 2024-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
