# Generated by Django 5.0.7 on 2024-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0004_video_created_at_video_description_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
