# Generated by Django 5.0.7 on 2024-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0007_remove_video_favorite_favoritevideo_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritevideo',
            name='favorite',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
