# Generated by Django 5.0.7 on 2024-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0008_remove_favoritevideo_favorite_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(default='all_videos', max_length=100),
        ),
    ]
