# Generated by Django 5.0.7 on 2024-08-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0009_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
    ]
