# Generated by Django 5.0.7 on 2024-09-21 11:57

import Video_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0010_video_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, storage=Video_App.models.VideoStorage(), upload_to='videos'),
        ),
    ]
