# Generated by Django 5.0.7 on 2024-09-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0011_alter_video_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='screenshot',
            new_name='image',
        ),
    ]
